apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: 192.168.16.40:3000/gitea-admin/fastapi:v1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 80
        tty: true