apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  ports:
    - name: fastapi-serivce
      nodePort: 31780
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: fastapi
  type: NodePort
